[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@oasisprotocol/=node_modules/@oasisprotocol/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std=lib/forge-std/src",
]
solc = "0.8.9"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
