/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameSecretiveSol from "./GameSecretive.sol";
export type { gameSecretiveSol };
export type { Poker } from "./Poker";
export * as factories from "./factories";
export type { Game } from "./GameSecretive.sol/Game";
export { Game__factory } from "./factories/GameSecretive.sol/Game__factory";
export type { GameSecretive } from "./GameSecretive.sol/GameSecretive";
export { GameSecretive__factory } from "./factories/GameSecretive.sol/GameSecretive__factory";
export { Poker__factory } from "./factories/Poker__factory";
